import pandas as pd

# Parse XML file and extract relevant interface information
def parse_xml(path_to_xml):
    '''
    Specifically designed to parse a PISA generated xml file
    :return: a df containing select interface features
    '''

    df = pd.read_xml(path_to_xml)

    # Save name of the two proteins participating in the interaction
    proteins = (df.loc[0]['STRUCTURENAME']).split('.')[0]

    # Save the number of hydrogen bonds
    feature_hbonds = (df.loc[4]['INTERFACENHBONDS'])

    # Save the number of salt bridges
    feature_saltbridges = (df.loc[4]['INTERFACENSALTBRIDGES'])

    # Save the number of salt bridges
    feature_disulfides = (df.loc[4]['INTERFACENDISULFIDEBONDS'])

    # Save the delta g of the interaction
    # The XML file generated by PISA is bad so interface area corresponds with delta G (Aug26,2022)
    feature_deltag = (df.loc[4]['INTERFACEAREA'])

    # Save the p value associated with the delta g of the interaction
    feature_deltagpvalue = (df.loc[4]['INTERFACEDELTAGPVALUE'])

    df = pd.DataFrame({
        'protA_protB': [proteins],
        'hbonds': [feature_hbonds],
        'saltbridges': [feature_saltbridges],
        'disulfides': [feature_disulfides],
        'deltag': [feature_deltag],
        'pvalue': [feature_deltagpvalue],
    })
    return df

xml_path = 'datasets\\xml_files\\ranked_0.xml'
parse_xml(xml_path)