import pandas as pd

# Parse XML file and extract relevant interface information
def parse_xml(path_to_xml):
    '''
    Specifically designed to parse a PISA generated xml file
    :return:
    '''

    df = pd.read_xml(path_to_xml)

    print(df.loc[4])

    # Save name of the two proteins participating in the interaction
    proteins = (df.loc[0]['STRUCTURENAME']).split('.')[0]

    # Save the number of hydrogen bonds
    feature_hbonds = (df.loc[4]['INTERFACENHBONDS'])
    print(feature_hbonds)

    # Save the number of salt bridges
    feature_saltbridges = (df.loc[4]['INTERFACENSALTBRIDGES'])
    print(feature_saltbridges)

    # Save the number of salt bridges
    feature_disulfides = (df.loc[4]['INTERFACENDISULFIDEBONDS'])
    print(feature_disulfides)

    # Save the delta g of the interaction
    # The XML file generated by PISA is bad so interface area corresponds with delta G (Aug26,2022)
    feature_deltag = (df.loc[4]['INTERFACEAREA'])
    print(feature_deltag)

    # Save the p value associated with the delta g of the interaction
    feature_deltagpvalue = (df.loc[4]['INTERFACEDELTAGPVALUE'])
    print(feature_deltagpvalue)

xml_path = 'datasets\\xml_files\\ranked_0.xml'
parse_xml(xml_path)